const books = [
  {
    id: 1,
    Name:"The Hate U Give",
    auther: " Angie ",
    category: "Fantasy",
    pages: 40,
    price: 100,
    image: "/img/6.png",
    instore:1,
  },
  {
    id: 2,
    Name:"Caraval",
    auther: " Garber",
    category: "Fantasy",
    pages: 70,
    price: 150,
    instore:1,
    image: "/img/2.png",
  },
  {
    id: 3,
    Name:"The Devouring Gray",
    auther: " Lynn",
    category: "Fantasy",
    pages: 25,
    price: 50,
    instore:1,
    image: "/img/3.png",
  },
  {
    id: 4,
    Name:"Nevernight ",
    auther: " Kristoff",
    category: "Fantasy",
    pages: 150,
    price: 200,
    instore:1,
    image: "/img/4.png",
  },
  {
    id: 5,
    Name:"The Wicked Deep ",
    auther: "Fantasy",
    category: "comedy",
    pages: 230,
    price: 220,
    instore:1,
    image: "/img/5.png",
  },
  {
    id: 6,
    Name:"Cerci",
    auther: "Madeline ",
    category: "Fantasy",
    pages: 35,
    price: 50,
    instore:1,
    image: "/img/1.png",
  },
];

export default books;
